{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "98adf924",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "number of processors:16\n",
      "Starting Burn in\n",
      "\n",
      "Burn in complete. Sampling posterior now.\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:354: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = -np.log((element_array*normalizer))\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n",
      "/Users/kenworthy/opt/anaconda3/lib/python3.9/site-packages/orbitize/priors.py:463: RuntimeWarning: invalid value encountered in log\n",
      "  lnprob = np.log(np.sin(element_array)/normalization)\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "10/10 steps completed\n",
      "Run complete\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import matplotlib.pyplot as plt\n",
    "from astropy.io import fits\n",
    "import emcee\n",
    "import paths\n",
    "import multiprocessing as mp\n",
    "\n",
    "import warnings\n",
    "warnings.filterwarnings('ignore')\n",
    "from orbitize import driver, read_input, results\n",
    "\n",
    "# FIX THE SEED SO THAT RESULTS ARE REPRODUCIBLE\n",
    "\n",
    "np.random.seed(44)\n",
    "\n",
    "# load in astrometry of V773 Tau\n",
    "orb_file = paths.data / \"apj416631t1_ascii_mod_2xerr.txt\"\n",
    "\n",
    "# MCMC parameters\n",
    "num_temps = 20\n",
    "num_walkers = 1000\n",
    "num_threads = mp.cpu_count()\n",
    "print(\"number of processors:{}\".format(num_threads))\n",
    "\n",
    "plx    = 7.70  # from Torres 2012 page 7 - better than GAIA as explicit solve using VLBI data\n",
    "plxerr = 0.19  # from Torres 2012 page 7\n",
    "\n",
    "myDriver = driver.Driver(\n",
    "    orb_file, # data file\n",
    "    'MCMC',        # choose from: ['OFTI', 'MCMC']\n",
    "    1,             # number of planets in system\n",
    "    5.27,          # total mass [M_sun] Boden 2012 Table 4\n",
    "    plx,         # system parallax [mas]\n",
    "    mass_err=0.65, # mass error [M_sun] Boden 2012 Table 4\n",
    "    plx_err=plxerr, # parallax error [mas]\n",
    "    mcmc_kwargs={'num_temps': num_temps, 'num_walkers': num_walkers, 'num_threads': num_threads}\n",
    ")\n",
    "\n",
    "# full run parameters\n",
    "total_orbits = 1000000 # number of steps x number of walkers (at lowest temperature)\n",
    "burn_steps = 2000 # steps to burn in per walker\n",
    "thin = 4\n",
    "\n",
    "# for testing\n",
    "#total_orbits = 10000 # number of steps x number of walkers (at lowest temperature)\n",
    "#burn_steps = 0 # steps to burn in per walker\n",
    "\n",
    "orbits = myDriver.sampler.run_sampler(total_orbits, burn_steps=burn_steps, thin=thin)\n",
    "\n",
    "hdf5_filename = paths.data / 'v773_tau_AB.hdf5'\n",
    "\n",
    "import os\n",
    "\n",
    "# To avoid weird behaviours, delete saved file if it already exists from a previous run of this notebook\n",
    "if os.path.isfile(hdf5_filename):\n",
    "    print('deleting old bundle {}'.format(hdf5_filename))\n",
    "    os.remove(hdf5_filename)\n",
    "    \n",
    "myResults = myDriver.sampler.results\n",
    "myResults.save_results(paths.data / 'v773_tau_AB.hdf5')"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "f4d183d7",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3 (ipykernel)",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.9.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
